// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-BPLQCE20qBV0SxyTVK33Xsg2MXciAB0',
    appId: '1:745109541289:web:895ad055fc46ad67dc34b8',
    messagingSenderId: '745109541289',
    projectId: 'chat-app-v1-8405f',
    authDomain: 'chat-app-v1-8405f.firebaseapp.com',
    storageBucket: 'chat-app-v1-8405f.appspot.com',
    measurementId: 'G-BRYG7MHMXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVDRRzvb6bSB1_Jjy36NBPizANfNByCtw',
    appId: '1:745109541289:android:23c45148b1a078addc34b8',
    messagingSenderId: '745109541289',
    projectId: 'chat-app-v1-8405f',
    storageBucket: 'chat-app-v1-8405f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFpjH8KIPtF01EbHmqM7tgyLxVx3ZwGa0',
    appId: '1:745109541289:ios:eb99c27fa9338f32dc34b8',
    messagingSenderId: '745109541289',
    projectId: 'chat-app-v1-8405f',
    storageBucket: 'chat-app-v1-8405f.appspot.com',
    iosClientId: '745109541289-tit4gbnri0ttojlhcoiet1ukppegaffa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatAppV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFpjH8KIPtF01EbHmqM7tgyLxVx3ZwGa0',
    appId: '1:745109541289:ios:eb99c27fa9338f32dc34b8',
    messagingSenderId: '745109541289',
    projectId: 'chat-app-v1-8405f',
    storageBucket: 'chat-app-v1-8405f.appspot.com',
    iosClientId: '745109541289-tit4gbnri0ttojlhcoiet1ukppegaffa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatAppV1',
  );
}
